// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/16/2025, 8:30:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/plugins/**/*.{js,ts,mjs}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/composables/**/*.{js,ts,mjs}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/utils/**/*.{js,ts,mjs}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/repoku/PBNU/persuratan/dashboardPersuratan/fe-digdayadash/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;